### ISSUE TITLE
Configuration Integrity Error

### ISSUE THREAD

**Issue by abpei** [jvde-github/AIS-catcher-control#1]
First of all: this is a great new addition, thanks for working on this!

- Updated AIS-Catcher to v0.61-35-gd9a9e291 which works fine. 
- Installed AIS-Catcher-Control after, set the password. Can log in, change password, start/stop service and read logs. Cannot edit configuration due to Configuration Integrity Error.
- The control.json has config_cmd_hash, and config_json_hash set, which appear to be calculated during install. 
- password_hash, is being changed with every password update. 

Any idea what might be causing this hash mismatch?

linux Architecture arm 
Build Version b75f807
CPUARMv7 Processor rev 4 (v7l)
Kernel Version 6.1.21-v7+

**Comment by jvde-github** [comment]
Hello!

Thanks for reaching out. 

This is by design. The input configuration for AIS-catcher is quite flexible and allows for some complex configuration. I could not replicate this in a UI in first instance. Therefore, the menus only work with our starting config JSON or any version amended by the UI. This is controlled by the hashes. It ensures the config.json is a bit more constrained and can be processed by the Web UI.


You can still set the settings in the Advanced section of the Web UI by editing the parameters there. But please note that config.json takes precedence. 

The other option is to start with fresh config files: sudo rm /etc/AIS-catcher and then run the two install scripts again.

Does this explain? Hopefully this will become easier over time.

**Comment by abpei** [comment]
Jasper,

That helped and worked! Thank you! I didn't know what the checks expected as default but deleting the config dir alongside a clean re-install of both Basic and Control worked flawlessly. 

It may prevent further questions to add a note in the docs that this is one way if anyone has a custom config and wishes to use the UI later. Of course, they will have to re-configure everything but with a UI that is really quick ;) This help page just states at the bottom that one can't use the editor when they already have a custom config. https://docs.aiscatcher.org/usage/gui/ 

Cheers,
Aaron

**Comment by jvde-github** [comment]
Thanks. I have added a warning to the install page and to the web gui section.
